name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: $/.github/actions/setup-nix
      - run: nix develop -c cargo audit

  cargo-deny:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: $/.github/actions/setup-nix
      - run: nix develop -c cargo deny check

  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: $/.github/actions/setup-nix
      - run: nix develop -c cargo fmt --all -- --check

  clippy:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: $/.github/actions/setup-nix
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cmd-format: nix develop -c {0}
      - run: nix develop -c cargo clippy --all-features -- --D warnings

  test:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - uses: $/.github/actions/setup-nix
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          cmd-format: nix develop -c {0}
      - run: nix develop -c cargo test --all-features

